name: Deploy versioned & latest

on:
  release:
    types: [published]

jobs:
  deploy-release:
    name: Deploy versioned images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build base image with nimbus dependencies (with expanded fs, otherwise is too small with latest tag
        run: docker build -t ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:buster-latest --build-arg FILE_SUFFIX=nimbus .
      - name: Tag the base image with the versioned tag
        run: docker tag ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:buster-latest ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:${{ steps.get_version.outputs.VERSION }}

      - name: Push images to ghcr.io
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:buster-latest
